name: Run TeleStars Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # خطوة إضافية لفك ضغط الملف برمجياً داخل السيرفر الافتراضي
    - name: Unzip TeleStars File
      run: |
        sudo apt-get install unzip -y
        unzip TeleStars.zip -d .
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # سيبحث عنrequirements داخل المجلد المستخرج
        pip install -r Download/requirements.txt || pip install -r requirements.txt

    - name: Run Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MNEMONIC: ${{ secrets.MNEMONIC }}
      run: |
        # تشغيل ملف main من داخل مجلد Download المستخرج
        python Download/main.py || python main.py
